version: '3'

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306" # expose for host
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    volumes:
      - .dbdata:/var/lib/mysql
  django:
    build: . # build Dockerfile image
    restart: always # restrart until connect
    ports:
      - "8000:8000" # expose for host
    volumes:
      - .:/usr/app/src # share with host
    depends_on: 
      - mysql
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
